print("Modern Calculator")
first=int(input("Enter the First Number = "))
second=int(input("Enter the Second Number = "))
print("The Addition of First number + Second Number is",first+second)
print("The Subtraction of First number - Second Number is",first-second)
print("The Multiplication of First number * Second Number is",first*second)
print("The Divide of First number / Second Number is",first/second)
print("The Modulus of First number % Second Number is",first%second)
print("The Exponentiation of First number ** Second Number is",first**second)
print("The Floor of First number // Second Number is",first//second)
print("You Got your Perfect Calculation ✌️")
